services:
  db:
    image: mariadb
    restart: "always"
    ports:
      - 3306:3306
    environment:
      # MARIADB_RANDOM_ROOT_PASSWORD: "no"
      MARIADB_ROOT_PASSWORD: "mariadb"
      MYSQL_DATABASE: "42api"
  api:
    image: apilabs
    restart: "always"
    depends_on:
      - db
    ports:
      - 8000:8000
      - 8001:8001
