services:
  db:
    image: mariadb
    ports:
     - 3306:3306

    environment:
      MARIADB_ROOT_PASSWORD: "mariadb"
      MARIADB_USER: "mariadb"
      MARIADB_PASSWORD: "mariadb"
    restart: "always"
  api:
    image: apilabs
    depends_on:
      - db
    ports:
     - 8000:8000
     - 8001:8001