services:
  db:
    container_name: labs-db
    image: mariadb
    restart: "always"
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "mariadb"
      MYSQL_DATABASE: "42api"

  api:
    container_name: labs-api
    image: apilabs:latest
    depends_on:
      - db
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      IP: "192.168.0.15"
